### ISSUE TITLE
이슈 예시

### ISSUE THREAD

**Issue by park12sj** [park12sj/bigdataBatch#1]
## 배포 단위별로 폴더 구성
- `/deploy` 인프라 타입에 따라 폴더 구분
ex)
- `/deploy/docker` 
- `/deploy/k8s` 
  ex) 
  - `deploy/k8s/common`
     - chart name - `...`
  - `deploy/k8s/app/common`
      - chart name - `...`
  - `deploy/k8s/app/appserve/...`
  - `deploy/k8s/app/appserve/...`
  - `deploy/k8s/app/model-gateway`

## 참고
- helm chart dependency
   - ...
   - ...
```
# requirements.yaml
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "..."
```
